### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by phmatray**
## Summary
I worked on JWT authentication trying to respect all the good practices already in place.
Currently, it works with the InMemoryDatabase but I broke some tests 😢 

## What changes did I make?
* Split the use case "Register" into "RegisterAccount" and "RegisterCustomer"

---
* Added the use case for authentication

---

## What remains to be done?
* [ ] Unit tests
* [ ] Documentation
* [ ] Discussion about design choices (password, secrets, config...)
* [ ] Technical review

## Linked issues
* Feature Request: JWT Authentication #87 
* Password value object #102

### CODE REVIEW

**Comment by alefcarlos** [comment]
What do you think about using an open source oath server, like KeyCloak to handle jwt and user registrations? keyCloak owns User domains and this project owns Customer domain.
And it will be simpler to write authorizations with scope.

**Comment by ivanpaulovich** [comment]
Hi @phmatray,

The way I see the `AuthenticateUseCase` it is a completely independent UseCase from the Wallet management. Actually I like the idea of authenticating the user credentials through an external service.

In other words, we could implement the AuthenticateUseCase using a fake service (always accepts the credentials) then invoke the `Presenter.Standard()` method passing those **External Credentials**. Then the JWT is generated in the Presenter exactly how you did.

Considering this, we add the authentication middleware to protect all Controllers.

The second part is to create the `RegisterWithExternalCredentialsUseCase` which will receive the credentials from the previous steps.

What do you think?

**Comment by phmatray** [comment]
That it's a great idea.
Thank you for this feedback. :)
I'll take care of it in the next few days.

**Comment by ivanpaulovich** [comment]
Hey @phmatray, would you be interested an be a contributor? That way you can review/merge PRs.

**Comment by narwhal3301** [comment]
If you think you have it -- https://narwhal3301.github.io/

**Comment by ivanpaulovich** [comment]
It was implemented with OAuth2 so the Authentication Service is not needed anymore. Thanks to all contributions!

**Pull request closed without merging**
